    

    export class Measurement {
        _id: string;
        MeasurementTakenBy: string;
        CustomerId: string;
        Inside: number;
        PentBottom: number;
        Knee: number;
        CoatLength: number;
        Cb: number;
        Hb: number;
        ShalwarKameezBottom: number;
        SLength: number;
        Bysep: number;
        Neck: number;
        Shoulder: number;
        Sleeve: number;
        Hip: number;
        Waist: number;
        Chest: number;
        ShalwarKameezLength: number;
        __v: number;
        TrouserInside?: number;
        TrouserBottom?: number;
        TrouserKnee?: number;
        TrouserLength?: number;
        TrouserHip?: number;
        TrouserWaist?: number;
        PentInside?: number;
        PentKnee?: number;
        PentLength?: number;
        PentHip?: number;
        PentWaist?: number;
        WaistCoatCB?: number;
        WaistCoatHB?: number;
        WaistCoatNeck?: number;
        WaistCoatShoulder?: number;
        WaistCoatHip?: number;
        WaistCoatWaist?: number;
        WaistCoatChest?: number;
        WaistCoatLength?: number;
        SherwaniBottom?: number;
        SherwaniHB?:number;
        SherwaniCB?: number;
        SherwaniBysep?: number;
        SherwaniNeck?: number;
        SherwaniShoulder?: number;
        SherwaniSleeve?: number;
        SherwaniHip?: number;
        SherwaniWaist?: number;
        SherwaniChest?: number;
        SherwaniLength?: number;
        CoatCB?: number;
        CoatHB?: number;
        CoatBysep?: number;
        CoatNeck?: number;
        CoatShoulder?: number;
        CoatSleeve?: number;
        CoatHip?: number;
        CoatWaist?: number;
        CoatChest?: number;
        ShalwarKameezSLength?: number;
        ShalwarKameezBysep?: number;
        ShalwarKameezNeck?: number;
        ShalwarKameezShoulder?: number;
        ShalwarKameezSleeve?: number;
        ShalwarKameezHip?: number;
        ShalwarKameezWaist?: number;
        ShalwarKameezChest?: number;
    }


